Likelion-wellcheers/wellcheers-Client

youknowho/src/pages/Home.jsx
youknowho/src/theme/theme.js

불필요 파일제거했습니다.(무시하세요)
- theme 파일 제거

[Refactor] 불필요 파일 제거

---

youknowho/src/component/layout/Nav.jsx

상단바 디자인 수정했습니다. 아마 상단바는 이대로 확정일듯.!
- 상단바 여백 줄이기
- 메뉴 이름 변경

[Design] 상단바 디자인 수정

---

youknowho/src/component/layout/Nav.jsx

페이지 경로를 전역변수로 설정
- 디자인 짜잘 수정
- 페이지 경로를 Recoil 전역변수로 설정
상단바 외 페이지에서 페이지 변경 필요시 (지도 찾기 -> 마이페이지 같은 큰 단위) recoil 가져와서 전역변수 바꿔주기
상단바 언더바 때문..

[Refactor] 페이지 전역변수로 설정

---

youknowho/package-lock.json
youknowho/src/pages/Home.jsx

홈 디자인 완료
- 홈 매거진 부분 디자인
- 반응형 웹 구현

[Design] 홈 매거진 디자인 홈디자인 완료

---

youknowho/package-lock.json
youknowho/src/App.js
youknowho/src/pages/localnews/Localinfo.jsx
youknowho/src/pages/localnews/Localnews.jsx
youknowho/src/pages/localnews/Search.jsx

[Design] 지역 검색 페이지 디자인

---

.gitignore
src/App.js
src/pages/searchHome/SearchHome.jsx
src/pages/searchHome/SearchMap.jsx

map 구현 필요한 파일 추가
- map 부분 라우터 추가
- 필요한 파일들 추가

[Docs] Map 필요한 파일 추가

---

public/index.html
src/component/modal/MapModal.jsx
src/pages/searchHome/SearchMap.jsx

- 지역 찾기 지도 부분 디자인
- 카카오 지도 가져오기
- 지역 찾기 모달 디자인 구현

[Feat] 지역 찾기 디자인 구현

---

src/App.js
src/component/modal/MapModal.jsx
src/pages/searchHome/CenterDetail.jsx
src/pages/searchHome/PostReview.jsx
src/pages/searchHome/SearchMap.jsx

센터 디테일 및 리뷰 작성 디자인
- 센터 디테일 페이지
- 리뷰 작성 페이지

[Feat] 센터 디테일 및 리뷰 작성 디자인

---

src/pages/mypage/Detailsavelist.jsx
src/pages/mypage/Editinfo.jsx
src/pages/mypage/Mypage.jsx
src/pages/mypage/Savelist.jsx

[Design] 마이페이지 부분 페이지들 디자인 틀 완성

---

src/component/layout/Nav.jsx
src/pages/Home.jsx

[Design] 홈 상단바 디자인 수정

---

src/pages/Home.jsx

[Design] 아까 못다한 디자인수정

---

package-lock.json
package.json
public/index.html
src/apis/recommend.js
src/pages/searchHome/SearchHome.jsx
src/pages/searchHome/SearchMap.jsx

필터 리스트 api 연결 및 그리고, 추천 지역 데이터 가져오기
- 필터리스트 api 연결 및 그리기
- 추천 지역 데이터 api 연결
- 디자인 수정

[Feat] 지역 추천 api

---

public/index.html
src/App.js
src/apis/recommend.js
src/component/layout/Nav.jsx
src/component/modal/MapModal.jsx
src/hooks/useForm.js
src/pages/searchHome/CalCost.jsx
src/pages/searchHome/CenterDetail.jsx
src/pages/searchHome/ReviewCenter.jsx
src/pages/searchHome/SearchHome.jsx
src/pages/searchHome/SearchMap.jsx

지역 및 시설 추천 정보 API 연결
- 지역 추천 리스트 띄우기
- 지역 폴리곤 및 마커 그리기
- 지역 기반 시설 추천 리스트 api 연결 및 띄우기
- 시설 디테일 페이지 api 연결 및 띄우기
- 시설 후기 컴포넌트 리팩토링
- 기타 디자인 수정

[Feat] 지역 및 시설 추천 정보 API 연결

---

src/pages/qusetionanswer/Wonderwrite.jsx

[Design] 질문 페이지 디자인 수정

---

src/pages/qusetionanswer/Wonderwrite.jsx

[Refactor] 지역 질문 오류 확인

---

src/component/RouterChangeListener.jsx
src/component/layout/Nav.jsx
src/pages/Home.jsx
src/pages/login/KakaoLogin.jsx
src/pages/searchHome/PostReview.jsx
src/recoil/isLoginState.js

로그인 / 로그아웃 구분 및 인식
- 로그인 안했을 시 지역 찾기, qna 페이지에서 로그인 페이지로 이동
- 로그아웃 기능 (액세스 토큰 제거)
- router 변경 시 로그인 여부 확인 (액세스 토큰 여부 확인)

[Fix] 로그인/로그아웃 구분 및 인식

---

src/pages/login/Login.jsx

[Test] uri

---

src/pages/mypage/Mypage.jsx

[Fix] mypage api

---

src/apis/account.js
src/apis/recommend.js
src/pages/mypage/Detailsavelist.jsx
src/pages/mypage/Mypage.jsx
src/pages/mypage/Savelist.jsx
src/pages/searchHome/CenterDetail.jsx

마이페이지 api 연결 완료
- 마이페이지 프로필 api 연결
- 마이페이지 시설 리뷰 api 연결
- 마이페이지 센터 리뷰 api 연결
- 마이페이지 저장 목록 api 연결 중

[Feat] 마이페이지 api 연결

---

src/App.js
src/pages/localnews/Localinfo.jsx
src/pages/localnews/Reviewpart.jsx
src/pages/mypage/Mypage.jsx
src/pages/searchHome/PostReview.jsx
src/pages/searchHome/Reviewing.jsx

지역 후기 쓰기
- 지역 후기 쓰기 및 리패토링
- 디자인

[Feat] 지역후기 쓰기 및 디자인

---

src/component/modal/MapModal.jsx

[Design] 모달창디자인

---

src/pages/qusetionanswer/Answer.jsx

real final

---

src/component/layout/Nav.jsx
src/hooks/useLogout.js
src/pages/qusetionanswer/Question.jsx

Nav.jsx 상단바 부분 리팩토링
logout 함수 hook으로 분리

상단바 부분 리팩토링

---

src/component/home/Article.jsx
src/component/home/Banner.jsx
src/component/home/Section.jsx
src/hooks/usePath.js
src/pages/Home.jsx

home 페이지 리팩토링
- 경로 이동 및 현재 페이지 설정 hook usePath 추가
- home -> Banner, Section, Article 세 부분으로 컴포넌트 분리

home 페이지 리팩토링

---

src/apis/recommend.js
src/component/home/Article.jsx
src/pages/Home.jsx
src/pages/searchHome/SearchHome.jsx

[Comment] SearchHome 주석 추가
